### ISSUE TITLE
Proposta: Link ai PDF

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/cors-dashboard#1]
Ciao @gabacode, che ne dici di inserire una cosa del genere prima del footer?

![image](https://user-images.githubusercontent.com/77018886/147254566-2d65d6f2-ed26-4539-ba50-2dafacae300f.png)

**Comment by dennisangemi** [comment]
Magari usiamo queste cards per gli ultimi bollettini e poi permettiamo agli utenti di premere un tasto "vedi tutti i bollettini" per accedere alla lista completa

**Comment by gabacode** [comment]
Sarebbe carino implementare delle slides che mostrino il contenuto a gruppi di 3-4

**Comment by dennisangemi** [comment]
> Sarebbe carino implementare delle slides che mostrino il contenuto a gruppi di 3-4

In che senso "mostrare contenuto"?

**Comment by dennisangemi** [comment]
Mi piacciono un sacco! Nella versione mobile sarebbe possibile mostrare 2 card per riga?

**Comment by gabacode** [comment]
Ho aggiunto una slide-slick, il numero di card per riga, a seconda della risoluzione, è modificabile dalle [options](https://github.com/opendatasicilia/cors-dashboard/blob/3a1fded5e9216da991fdbeefb021f4cb9947abaa/src/components/Reports.js#L41)
