### ISSUE TITLE
Sostituire netlify con nuovo URL

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/cors-dashboard#10]
https://report-dasoe.opendatasicilia.it/

- [x] README InformaCOVID
- [x] bozza wp
- [x] Repo cors-dashboard

**Comment by dennisangemi** [comment]
Ciao @gabacode io non posso modificare questo. Per favore ci pensi tu? thx
![image](https://user-images.githubusercontent.com/77018886/147660612-c09c452a-cc56-4a44-8bee-e2176ff90d94.png)

**Comment by gabacode** [comment]
@dennisangemi neanche io, mi sa che spostando l'ownership del repo non sono piu administrator ma semplicemente contributor. Forse, senza impegno, puo' darci un'occhiata @aborruso?

**Comment by aborruso** [comment]
> @dennisangemi neanche io, mi sa che spostando l'ownership del repo non sono piu administrator ma semplicemente contributor. Forse, senza impegno, puo' darci un'occhiata @aborruso?

ora siete mantain. Riuscite?

![image](https://user-images.githubusercontent.com/30607/147671524-095fdd3c-2fbb-4605-ae92-acd45b528a4f.png)

**Comment by dennisangemi** [comment]
> Riuscite?

Yes! Grazie mille

**Comment by gabacode** [comment]
Ora si, grazie mille Andrea!

**Comment by dennisangemi** [comment]
@gabacode se non devi apportare modifiche al codice (o hai già fatto) possiamo chiudere questa issue

**Comment by gabacode** [comment]
@dennisangemi puoi chiudere!

**Comment by dennisangemi** [comment]
thx
