### ISSUE TITLE
codice istat come parametro URL

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/cors-dashboard#17]
Ciao @gabacode, se non ricordo male avevi implementato questa feature ma non la trovo documentata (e non ricordo la sintassi). Per favore potresti scrivere 2 righe nel readme? Grazie ;)

**Comment by gabacode** [comment]
Ho aggiunto le info al README via 632445a

**Comment by dennisangemi** [comment]
Grazie mille!
