### ISSUE TITLE
Proposta info ℹ️

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/cors-dashboard#4]
Sarebbe veramente figo inserire un tasto info ℹ️ sui widget in modo tale da inserire dettagli relativi alla semantica (prelevandoli dallo [schema dati](https://github.com/opendatasicilia/covid-open-report-sicilia#schema-dati) ). Conosco gente che sarebbe veramente contenta di una funzionalità del genere ;). 

Edit: Scusami ho fatto un casino con la chiusura e la riapertura della issue haha

**Comment by gabacode** [comment]
@dennisangemi come ti sembra? Se per te è ok chiudiamo questa issue

**Comment by dennisangemi** [comment]
@gabacode sono bellissime, l'unica cosa che va sistemata è il popup di incidenza e vaccinati per mobile (troncato)
