### ISSUE TITLE
Dominio di terzo livello

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/cors-dashboard#5]
- reportdasoe.opendatasicilia.it
- **report-dasoe.opendatasicilia.it**
- corsdashboard.opendatasicilia.it
- cors-dashboard.opendatasicilia.it

**Comment by gabacode** [comment]
@aborruso credi sia il caso pubblicare la nuova Dashboard come report-dasoe.opendatasicilia.it ?

**Comment by dennisangemi** [comment]
Ciao @aborruso, l'unica cosa che manca (prima di effettuare il lancio) è il dominio di terzo livello. Potresti per favore occupartene (quando puoi)? Potremmo utilizzare `report-dasoe.opendatasicilia.it `
