### ISSUE TITLE
Analytics & cookie policy

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/cors-dashboard#6]
Potremmo usare la stessa CP del sito opendatasicilia.it? E il popup di [informacovid](https://github.com/opendatasicilia/informa-covid19/commit/2e61e917b370be0082c3f915fc6f694c958f6abe)?

**Comment by dennisangemi** [comment]
Gli analytics vanno inseriti [qui](https://github.com/gabacode/cors-dashboard/blob/main/public/index.html)? posso provare io?

**Comment by gabacode** [comment]
@dennisangemi Si, per il minimo utilizzo che dobbiamo farne credo (view counts) puoi inserirli all'interno del public.html
![8-paste-the-site-tag](https://user-images.githubusercontent.com/38985346/147357714-525973fb-d739-434b-aafe-8af626d408c7.png)
Credits: [https://tamalweb.com/](https://tamalweb.com/google-analytics-with-reactjs)

**Comment by dennisangemi** [comment]
Fatto! Funziona ;)

**Comment by dennisangemi** [comment]
@gabacode  io ho creato una GA4. Forse è meglio una UA? Non ne capisco tantissimo. dimmi tu ;)
