### ISSUE TITLE
Netlify deploy

### ISSUE THREAD

**Issue by gabacode** [opendatasicilia/cors-dashboard#7]
Ho spostato l'ownership del repository dal mio a quello di opendatasicilia. Purtroppo non sono riuscito a collegarlo a netlify come organisation, forse mi manca qualche permesso? @aborruso ti è arrivata qualche email a riguardo?

**Comment by dennisangemi** [comment]
Infatti purtroppo il link non funziona più:(

**Comment by aborruso** [comment]
Buongiorno!

Ho autorizzato adesso @gabacode 

Non sarebbe meglio (a memoria mi sembrava di averlo già proposto), creare un account netlify ODS e intermediare la cosa tramite quello? Ovviamente @gabacode tu avresti tutti i token e simili del caso e le credenziali netlify

**Comment by gabacode** [comment]
Grazie @aborruso! 
Si, effettivamente avere un account condiviso sarebbe meglio. Per qualche motivo credevo che i progetti aggiunti tramite il mio account potessero riflettersi anche sull'account ODS. Va bene allora, muoviamoci verso quella direzione, credo che sia molto piu sistemato :)

edit: nel frattempo ho rifatto il deploy su https://dasoe-report.netlify.app/ - funzia!

**Comment by aborruso** [comment]
Ciao @gabacode creato account netlify per ODS.

Mi dici adesso il primo passo? Importo il repo con qualche settaggio particolare?


![image](https://user-images.githubusercontent.com/30607/147414739-183ea56b-487d-45f5-8b80-163c4554da9a.png)

**Comment by gabacode** [comment]
Ciao @aborruso , dovrebbe rilevare i settaggi automaticamente. Quindi il primo passo sarebbe Import from Git > Selezionare il repository "cors-dashboard". Se dovesse chiedere, gli unici comandi che potrebbero differenziare questa app al momento sono:

Branch deploy: main
Build command: yarn build
Publish directory: build

**Comment by aborruso** [comment]
@gabacode ho fatto quello che dovevo fare e chiudo.

Ti scrivo email con credenziali, così nel caso "aggiusti" lato netlify

**Comment by aborruso** [comment]
https://vibrant-swartz-2d9fb0.netlify.app/

**Comment by gabacode** [comment]
Grazie @aborruso !
