### ISSUE TITLE
Normalizzare percentuali tenendo conto del target >=5

### ISSUE THREAD

**Issue by gabacode** [opendatasicilia/cors-dashboard#8]
- <del>[ ] Grafico percentuali vaccinati/immunizzati</del>
- [x] Grafico stima vaccinati/immunizzati settimanali

**Comment by gabacode** [comment]
Un piccolo aggiornamento: parlando con mio padre riguardo il "ribilanciamento", mi ha suggerito che non ha molto senso "correggere" le percentuali retroattivamente, perche' relative ad un altro target, in ogni caso. @dennisangemi lasciamo il grafico a linee "percentuali vaccinati/immunizzati" cosi' com'e'?

**Comment by dennisangemi** [comment]
>  @dennisangemi lasciamo il grafico a linee "percentuali vaccinati/immunizzati" cosi' com'e'?

Secondo me sì, al massimo scriviamo due righe di spiegazione (variazione target)
