### ISSUE TITLE
Creare dominio terzo livello

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/cors-dashboard#9]
Ciao @aborruso, l'unica cosa che manca (prima di effettuare il lancio) è il dominio di terzo livello. Potresti per favore occupartene (quando puoi)? Potremmo utilizzare `report-dasoe.opendatasicilia.it `

_Originally posted by @dennisangemi in https://github.com/opendatasicilia/cors-dashboard/issues/5#issuecomment-1001623252_

**Comment by gabacode** [comment]
Netlify suggerisce di collegare il CNAME così:  
`report-dasoe CNAME dasoe-report.netlify.app.`

**Comment by aborruso** [comment]
Appena fatto, ma ci vorrà un po' per gli esiti.
Chiudo.

Grazie

**Comment by dennisangemi** [comment]
Grazie mille @aborruso ! Adesso funziona https://report-dasoe.opendatasicilia.it/ ;)
